"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class fr3_state(object):

    __slots__ = ["timestamp", "q", "dq", "T", "M", "G", "C"]

    __typenames__ = ["int64_t", "double", "double", "double", "double", "double", "double"]

    __dimensions__ = [None, [7], [7], [7], [49], [7], [7]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.q = [ 0.0 for dim0 in range(7) ]
        """ LCM Type: double[7] """
        self.dq = [ 0.0 for dim0 in range(7) ]
        """ LCM Type: double[7] """
        self.T = [ 0.0 for dim0 in range(7) ]
        """ LCM Type: double[7] """
        self.M = [ 0.0 for dim0 in range(49) ]
        """ LCM Type: double[49] """
        self.G = [ 0.0 for dim0 in range(7) ]
        """ LCM Type: double[7] """
        self.C = [ 0.0 for dim0 in range(7) ]
        """ LCM Type: double[7] """

    def encode(self):
        buf = BytesIO()
        buf.write(fr3_state._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>7d', *self.q[:7]))
        buf.write(struct.pack('>7d', *self.dq[:7]))
        buf.write(struct.pack('>7d', *self.T[:7]))
        buf.write(struct.pack('>49d', *self.M[:49]))
        buf.write(struct.pack('>7d', *self.G[:7]))
        buf.write(struct.pack('>7d', *self.C[:7]))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != fr3_state._get_packed_fingerprint():
            raise ValueError("Decode error")
        return fr3_state._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = fr3_state()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.q = struct.unpack('>7d', buf.read(56))
        self.dq = struct.unpack('>7d', buf.read(56))
        self.T = struct.unpack('>7d', buf.read(56))
        self.M = struct.unpack('>49d', buf.read(392))
        self.G = struct.unpack('>7d', buf.read(56))
        self.C = struct.unpack('>7d', buf.read(56))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if fr3_state in parents: return 0
        tmphash = (0x46eb1ebab2cd1a79) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if fr3_state._packed_fingerprint is None:
            fr3_state._packed_fingerprint = struct.pack(">Q", fr3_state._get_hash_recursive([]))
        return fr3_state._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", fr3_state._get_packed_fingerprint())[0]

