"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class fr3_state(object):
    __slots__ = ["timestamp", "q", "dq", "T"]

    __typenames__ = ["int64_t", "double", "double", "double"]

    __dimensions__ = [None, [7], [7], [7]]

    def __init__(self):
        self.timestamp = 0
        self.q = [ 0.0 for dim0 in range(7) ]
        self.dq = [ 0.0 for dim0 in range(7) ]
        self.T = [ 0.0 for dim0 in range(7) ]

    def encode(self):
        buf = BytesIO()
        buf.write(fr3_state._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>7d', *self.q[:7]))
        buf.write(struct.pack('>7d', *self.dq[:7]))
        buf.write(struct.pack('>7d', *self.T[:7]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != fr3_state._get_packed_fingerprint():
            raise ValueError("Decode error")
        return fr3_state._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = fr3_state()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.q = struct.unpack('>7d', buf.read(56))
        self.dq = struct.unpack('>7d', buf.read(56))
        self.T = struct.unpack('>7d', buf.read(56))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if fr3_state in parents: return 0
        tmphash = (0xe22883fb178c4740) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if fr3_state._packed_fingerprint is None:
            fr3_state._packed_fingerprint = struct.pack(">Q", fr3_state._get_hash_recursive([]))
        return fr3_state._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", fr3_state._get_packed_fingerprint())[0]

